### ISSUE TITLE
missing: rendertype_entity_glint_direct

### ISSUE THREAD

**Issue by McTsts** [McTsts/Minecraft-Shaders-Wiki#2]

**Comment by McTsts** [comment]
Tested with:
- Item: Diamond Sword, Stick, Nether Star (held, dropped, item frame, inventory)
- Generic: Stone, Oak Leaves (held, dropped, item frame, inventory)
- Glass: Glass, Lime Stained Glass, Lime Stained Glass Pane (held, dropped, item frame, inventory)
- Armor: Leather Chestplate, Diamond Chestplate (held, dropped, item frame, armor stand, worn, inventory)

Affects:
- None of the things I tested

**Comment by bradleyq** [comment]
I found it is for enchanted tridents in hand and in the world. There may be more.

**Comment by McTsts** [comment]
Fixed by bradleyq
