### ISSUE TITLE
position_color_tex is also used for inwalloverlay

### ISSUE THREAD

**Issue by Alex81341** [McTsts/Minecraft-Shaders-Wiki#27]
![image](https://github.com/McTsts/Minecraft-Shaders-Wiki/assets/87265332/171ad0d4-9414-4854-a317-650dd2c51b5e)
![image](https://github.com/McTsts/Minecraft-Shaders-Wiki/assets/87265332/210a5b75-f97d-4b95-8d42-c4901e732b53)
![image](https://github.com/McTsts/Minecraft-Shaders-Wiki/assets/87265332/55be0829-d6a6-49a6-baaa-181817e76112)

**Comment by McTsts** [comment]
Thanks, adding that
