### ISSUE TITLE
missing: rendertype_glint_translucent

### ISSUE THREAD

**Issue by McTsts** [McTsts/Minecraft-Shaders-Wiki#5]

**Comment by McTsts** [comment]
Tested with:
- Item: Diamond Sword, Stick, Nether Star (1st PoV held, 3rd PoV held, dropped, item frame, inventory)
- Block: Stone, Oak Leaves (1st PoVheld, 3rd PoV held, dropped, item frame, inventory)
- Glass: Glass, Lime Stained Glass, Lime Stained Glass Pane (1st PoV held, 3rd PoV held, dropped, item frame, inventory)
- Armor: Leather Chestplate, Diamond Chestplate (1st PoVheld, 3rd PoV held, dropped, item frame, armor stand, worn, inventory)

Affects:
- Affected none of these

**Comment by DartCat25** [comment]
`rendertype_glint_tranlucent` is showing on translucent items (like stained glass) in world when graphics setting is `Fabolous!`
[Commit](https://github.com/McTsts/Minecraft-Shaders-Wiki/commit/28182a018deaf57fe8c04d17564a1bf67a6943d6).
